# host is from `docker-machine ip default`
development:
  dialect: postgres
  datasource: "host=172.18.0.2 port=5432 user=postgres password=c4chec4sh dbname=publisher sslmode=disable"
  dir: "../migrations/"
  table: migrations
