# host is from `docker-machine ip default`
development:
  dialect: postgres
  datasource: "host=127.0.0.1 port=5434 user=postgres dbname=publisher sslmode=disable"
  dir: "../migrations/"
  table: migrations

docker-tests:
  dialect: postgres
  datasource: host=publisher-db port=5432 user=cachecash password=publisherDB dbname=publisher sslmode=disable 
  dir: publisher/migrations/
  table: migrations
