language: go

before_script:
- git lfs pull
- go get -u github.com/rubenv/sql-migrate/...
- go get -u github.com/volatiletech/sqlboiler/...
- go get -u github.com/volatiletech/sqlboiler-sqlite3/...
- go get -u github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql/...
- go get -u github.com/alecthomas/gometalinter/...
- go get -u github.com/kisielk/errcheck

script:
- go test -v -race -tags=sqlboiler_test ./...
# linting is non-fatal right now
- gometalinter --vendor --disable-all --deadline=10m
  --enable=errcheck --enable=vet --enable=vetshadow
  -e "cache/models/boil_types.go" -e "cache/models/logical_cache_mapping.go"
  ./... || true
