---
version: '3.7'
services:
  upstream:
    image: nginx
    ports:
    - 8081:80
    volumes:
    - ./testdata/content:/usr/share/nginx/html

  upstream-apache:
    image: httpd
    ports:
    - 8091:80
    volumes:
    - ./testdata/content:/usr/local/apache2/htdocs

  upstream-lighttpd:
    build: deploy/httpds/lighttpd
    ports:
    - 8092:80
    volumes:
    - ./testdata/content:/var/www/localhost/htdocs

  upstream-caddy:
    build: deploy/httpds/caddy
    ports:
    - 8093:80
    volumes:
    - ./testdata/content:/var/www

  upstream-python:
    image: python:3-alpine
    command: python -m http.server -d /var/www 80
    init: true
    ports:
    - 8094:80
    volumes:
    - ./testdata/content:/var/www

  publisher:
    image: cachecash/go-cachecash
    build: .
    command: publisherd -logLevel debug -trace http://jaeger:14268
    ports:
    - 7070:7070
    - 8043:8043
    # status
    - 8100:8100
    environment:
    - PUBLISHER_PUBLISHER_ADDR=publisher:7070
    - PUBLISHER_UPSTREAM=${PUBLISHER_UPSTREAM:-http://upstream:80}
    - PUBLISHER_BOOTSTRAP_ADDR=bootstrapd:7777
    - PUBLISHER_DATABASE=host=publisher-db port=5432 user=postgres dbname=publisher sslmode=disable
    volumes:
    - ./data/publisher:/data

  publisher-db:
    image: postgres:11
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=publisher

  bootstrapd:
    image: cachecash/go-cachecash
    build: .
    command: bootstrapd -logLevel debug -trace http://jaeger:14268
    ports:
    - 7777:7777
    # status
    - 8101:8100
    volumes:
    - ./data/bootstrapd:/data

  cache-0:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -trace http://jaeger:14268
    ports:
    - 9000:9000
    - 9443:9443
    # status
    - 7100:9100
    environment:
    - CACHE_BOOTSTRAP_ADDR=bootstrapd:7777
    volumes:
    - ./data/cache-0:/data

  cache-1:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -trace http://jaeger:14268
    ports:
    - 9001:9000
    - 9444:9443
    # status
    - 7101:9100
    environment:
    - CACHE_BOOTSTRAP_ADDR=bootstrapd:7777
    volumes:
    - ./data/cache-1:/data

  cache-2:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -trace http://jaeger:14268
    ports:
    - 9002:9000
    - 9445:9443
    # status
    - 7102:9100
    environment:
    - CACHE_BOOTSTRAP_ADDR=bootstrapd:7777
    volumes:
    - ./data/cache-2:/data

  cache-3:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -trace http://jaeger:14268
    ports:
    - 9003:9000
    - 9446:9443
    - 7103:9100
    environment:
    - CACHE_BOOTSTRAP_ADDR=bootstrapd:7777
    volumes:
    - ./data/cache-3:/data

  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    # UI
    - 16686:16686
    - 14268:14268
    - 9411:9411
...
