---

# ./bin/generate-config -outputPath cfg/ -upstream http://upstream:80 -publisherCacheServiceAddr publisher:8082

version: '3.7'
services:
  upstream:
    image: nginx
    ports:
    - 8081:80
    volumes:
    - ./testdata/content:/usr/share/nginx/html

  upstream-apache:
    image: httpd
    ports:
    - 8091:80
    volumes:
    - ./testdata/content:/usr/local/apache2/htdocs

  upstream-lighttpd:
    build: deploy/httpds/lighttpd
    ports:
    - 8092:80
    volumes:
    - ./testdata/content:/var/www/localhost/htdocs

  upstream-caddy:
    build: deploy/httpds/caddy
    ports:
    - 8093:80
    volumes:
    - ./testdata/content:/var/www

  upstream-python:
    image: python:3-alpine
    command: python -m http.server -d /var/www 80
    init: true
    ports:
    - 8094:80
    volumes:
    - ./testdata/content:/var/www

  publisher:
    image: cachecash/go-cachecash
    build: .
    command: publisherd -logLevel debug -config /etc/publisher.config.json
    ports:
    - 8080:8080
    - 8082:8082
    - 8043:8043
    volumes:
    - ./cfg/publisher.config.json:/etc/publisher.config.json

  publisher-db:
    image: postgres:11
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=publisher

  bootstrapd:
    build: .
    command: bootstrapd -logLevel debug -config /etc/bootstrapd.config.json
    ports:
    - 7777:7777
    volumes:
    - ./cfg/bootstrapd.config.json:/etc/bootstrapd.config.json

  cache-0:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -config /etc/cached.config.json
    ports:
    - 9000:9000
    - 9443:9443
    - 7100:9100
    volumes:
    - ./cfg/cache-0.config.json:/etc/cached.config.json
    - ./cache-0:/cache-0

  cache-1:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -config /etc/cached.config.json
    ports:
    - 9001:9001
    - 9444:9444
    - 7101:9100
    volumes:
    - ./cfg/cache-1.config.json:/etc/cached.config.json
    - ./cache-1:/cache-1

  cache-2:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -config /etc/cached.config.json
    ports:
    - 9002:9002
    - 9445:9445
    - 7102:9100
    volumes:
    - ./cfg/cache-2.config.json:/etc/cached.config.json
    - ./cache-2:/cache-2

  cache-3:
    image: cachecash/go-cachecash
    build: .
    command: cached -logLevel debug -config /etc/cached.config.json
    ports:
    - 9003:9003
    - 9446:9446
    - 7103:9100
    volumes:
    - ./cfg/cache-3.config.json:/etc/cached.config.json
    - ./cache-3:/cache-3
...
