
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/jonboulle/clockwork"
  version = "0.1.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"
  version = "1.3.2"

[[constraint]]
  name = "github.com/rubenv/sql-migrate"
  branch = "master"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.0.3"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  # this points to 2.0.0-rc.2, but specifying that as a version doesn't work correctly
  #version = "2.0.0-rc.2"
  revision = "deee8c7ae70bab412e4f10cfa068e0be61a8d0eb"

[[constraint]]
  name = "github.com/improbable-eng/grpc-web"
  version = "0.6.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.11.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
